-- ALL MOVIE
DROP VIEW IF EXISTS ALL_MOVIE CASCADE;
CREATE VIEW ALL_MOVIE AS (
    SELECT id, title, year, 'Comedy' AS genre
    FROM comedymovie
    UNION
    SELECT id, title, year, 'NonComedy' AS genre
    FROM noncomedymovie
    );

DROP MATERIALIZED VIEW IF EXISTS ALL_MOVIE_MAT CASCADE;
CREATE MATERIALIZED VIEW ALL_MOVIE_MAT AS (
    SELECT id, title, year, 'Comedy' AS genre
    FROM comedymovie
    UNION
    SELECT id, title, year, 'NonComedy' AS genre
    FROM noncomedymovie
    );

-- ALL ACTOR
DROP VIEW IF EXISTS ALL_ACTOR CASCADE;
CREATE VIEW ALL_ACTOR AS (
    SELECT *
    FROM ComedyActor
    UNION
    SELECT *
    FROM NonComedyActor
    );

DROP MATERIALIZED VIEW IF EXISTS ALL_ACTOR_MAT CASCADE;
CREATE MATERIALIZED VIEW ALL_ACTOR_MAT AS (
    SELECT *
    FROM ComedyActor
    UNION
    SELECT *
    FROM NonComedyActor
    );

-- ALL MOVIE ACTOR
DROP VIEW IF EXISTS ALL_MOVIE_ACTOR CASCADE;
CREATE VIEW ALL_MOVIE_ACTOR AS (
    SELECT * 
    FROM ActedIn
);

DROP MATERIALIZED VIEW IF EXISTS ALL_MOVIE_ACTOR_MAT CASCADE;
CREATE MATERIALIZED VIEW ALL_MOVIE_ACTOR_MAT AS (
    SELECT * 
    FROM ActedIn
);